### ISSUE TITLE
Would you consider adding an Open source Licence?

### ISSUE THREAD

**Issue by harlantwood** [Amazingca/BSKY-Wrapper#21]
Hi, first, amazing work, much appreciated!  I’ve browsed your code and found it clean and readable. 🥳

Would you be open to adding an open source license so that others like me could build on (and contribute to) your great work?

Thanks for considering!  🙏

**Comment by Amazingca** [comment]
Hey Harlan!

Thanks for your interest in the project! I see no problem with adding an open-source license. I should be able to set that up sometime later today. Until then, I'll leave this issue open.

**Comment by harlantwood** [comment]
Awesome, thanks! 🙏

**Comment by Amazingca** [comment]
Added GNU General Public License v3.0 to the repo. Marking this issue as closed. 👍
